### ISSUE TITLE
bluepyopt in JUSUF

### ISSUE THREAD

**Issue by clupascu** [BlueBrain/spack#1215]
Hi,

when running a bluepyopt on JUSUF I get 

File "opt_neuron.py", line 38, in <module>
    import bluepyopt
  File "/p/project/icei-hbp-2020-0013/software-deployment/HBP/jusuf/03-06-2021/install/linux-centos7-zen2/gcc-9.3.0/py-bluepyopt-1.9.37-eght6z/lib/python3.8/site-packages/bluepyopt/__init__.py", line 33, in <module>
    import bluepyopt.deapext.optimisations
  File "/p/project/icei-hbp-2020-0013/software-deployment/HBP/jusuf/03-06-2021/install/linux-centos7-zen2/gcc-9.3.0/py-bluepyopt-1.9.37-eght6z/lib/python3.8/site-packages/bluepyopt/deapext/optimisations.py", line 31, in <module>
Traceback (most recent call last):
  File "opt_neuron.py", line 38, in <module>
    import bluepyopt
  File "/p/project/icei-hbp-2020-0013/software-deployment/HBP/jusuf/03-06-2021/install/linux-centos7-zen2/gcc-9.3.0/py-bluepyopt-1.9.37-eght6z/lib/python3.8/site-packages/bluepyopt/__init__.py", line 33, in <module>
    import deap.algorithms
  File "/p/project/icei-hbp-2020-0013/software-deployment/HBP/jusuf/03-06-2021/install/linux-centos7-zen2/gcc-9.3.0/py-deap-1.3.1-l5a6rg/lib/python3.8/site-packages/deap/algorithms.py", line 30, in <module>
    from . import tools
    import bluepyopt.deapext.optimisations
  File "/p/project/icei-hbp-2020-0013/software-deployment/HBP/jusuf/03-06-2021/install/linux-centos7-zen2/gcc-9.3.0/py-deap-1.3.1-l5a6rg/lib/python3.8/site-packages/deap/tools/__init__.py", line 25, in <module>
  File "/p/project/icei-hbp-2020-0013/software-deployment/HBP/jusuf/03-06-2021/install/linux-centos7-zen2/gcc-9.3.0/py-bluepyopt-1.9.37-eght6z/lib/python3.8/site-packages/bluepyopt/deapext/optimisations.py", line 31, in <module>
    from .emo import *
  File "/p/project/icei-hbp-2020-0013/software-deployment/HBP/jusuf/03-06-2021/install/linux-centos7-zen2/gcc-9.3.0/py-deap-1.3.1-l5a6rg/lib/python3.8/site-packages/deap/tools/emo.py", line 9, in <module>
    import deap.algorithms
    import numpy
  File "/p/project/icei-hbp-2020-0013/software-deployment/HBP/jusuf/03-06-2021/install/linux-centos7-zen2/gcc-9.3.0/py-deap-1.3.1-l5a6rg/lib/python3.8/site-packages/deap/algorithms.py", line 30, in <module>
  File "/p/project/icei-hbp-2020-0013/software-deployment/HBP/jusuf/03-06-2021/install/linux-centos7-zen2/gcc-9.3.0/py-numpy-1.19.4-zar5bv/lib/python3.8/site-packages/numpy/__init__.py", line 292
SyntaxError: Non-ASCII character '\xef' in file /p/project/icei-hbp-2020-0013/software-deployment/HBP/jusuf/03-06-2021/install/linux-centos7-zen2/gcc-9.3.0/py-numpy-1.19.4-zar5bv/lib/python3.8/site-packages/numpy/__init__.py on line 293, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
    from . import tools
  File "/p/project/icei-hbp-2020-0013/software-deployment/HBP/jusuf/03-06-2021/install/linux-centos7-zen2/gcc-9.3.0/py-deap-1.3.1-l5a6rg/lib/python3.8/site-packages/deap/tools/__init__.py", line 25, in <module>
    from .emo import *
  File "/p/project/icei-hbp-2020-0013/software-deployment/HBP/jusuf/03-06-2021/install/linux-centos7-zen2/gcc-9.3.0/py-deap-1.3.1-l5a6rg/lib/python3.8/site-packages/deap/tools/emo.py", line 9, in <module>
    import numpy
  File "/p/project/icei-hbp-2020-0013/software-deployment/HBP/jusuf/03-06-2021/install/linux-centos7-zen2/gcc-9.3.0/py-numpy-1.19.4-zar5bv/lib/python3.8/site-packages/numpy/__init__.py", line 292
SyntaxError: Non-ASCII character '\xef' in file /p/project/icei-hbp-2020-0013/software-deployment/HBP/jusuf/03-06-2021/install/linux-centos7-zen2/gcc-9.3.0/py-numpy-1.19.4-zar5bv/lib/python3.8/site-packages/numpy/__init__.py on line 293, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

The modules that I load are

module use /p/project/icei-hbp-2020-0013/software-deployment/HBP/jusuf/03-06-2021/modules/tcl/linux-centos7-zen2/

# always load neuron module
module load neuron/8.0.0

# load only relevant modules needed for your job
module load py-bluepyopt

Any suggestion?

**Comment by jorblancoa** [comment]
Have you loaded python also?
`module load Python/3.8.5 SciPy-Stack/2020-Python-3.8.5`

**Comment by clupascu** [comment]
I was indeed skipping that module load. 

Now I get one other error (that I was probably getting also before) while compiling the mod files.

/p/software/jusuf/stages/2020/software/psmpi/5.4.7-1-iccifort-2020.2.254-GCC-9.3.0-mt/bin/mpicc: line 302: icc: command not found
make: *** [mod_func.o] Error 127
make: *** Waiting for unfinished jobs....

**Comment by jorblancoa** [comment]
You have to load also those
`module load Intel/2020.2.254-GCC-9.3.0 ParaStationMPI/5.4.7-1 HDF5`

Sorry in the part of python I didn't include the extra modules needed, but they were in the part of simulation only.
I will update the wiki accordingly.

**Comment by pramodk** [comment]
Thanks @jorblancoa !

Wiki is updated. please let us know if you see any issue.

**Comment by clupascu** [comment]
Everything works now. I am closing the ticket. Thank you again.
