### ISSUE TITLE
Build issues with spykfunc

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/spack#144]
Here are troubles I am having:

First of all, sub-module cloning with ssh doesn't work on compute node? : 

```
loy$ git clone --recursive ssh://bbpcode.epfl.ch/building/Spykfunc
Cloning into 'Spykfunc'...
remote: Counting objects: 404, done
remote: Finding sources: 100% (145/145)
remote: Total 2825 (delta 67), reused 2774 (delta 67)
Receiving objects: 100% (2825/2825), 75.18 MiB | 23.69 MiB/s, done.
Resolving deltas: 100% (1917/1917), done.
Submodule 'deps/hadoken' (git@github.com:adevress/hadoken.git) registered for path 'deps/hadoken'
Submodule 'deps/mvd-tool' (https://github.com/BlueBrain/MVDTool.git) registered for path 'deps/mvd-tool'
Cloning into 'deps/hadoken'...
ssh: connect to host github.com port 22: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:adevress/hadoken.git' into submodule path 'deps/hadoken' failed
```

I think we should change this to https ?

**Comment by pramodk** [comment]
Seems like mirror removes .git directory (fetch strategy setting `clear=False` is not respected) : 

```
==> Staging archive: /gpfs/bbp.cscs.ch/apps/hpc/test/kumbhar/spack-deploy/workspace/HOME_DIR/spack/var/spack/stage/spykfunc-0.11.0-x6wl5osfi6nexkherkaxrbgwkz3ydjk3/spykfunc-0.11.0.tar.gz
==> Created stage in /gpfs/bbp.cscs.ch/apps/hpc/test/kumbhar/spack-deploy/workspace/HOME_DIR/spack/var/spack/stage/spykfunc-0.11.0-x6wl5osfi6nexkherkaxrbgwkz3ydjk3
==> No patches needed for spykfunc
==> Building spykfunc [PythonPackage]
==> Executing phase: 'build'
==> '/gpfs/bbp.cscs.ch/apps/hpc/test/kumbhar/spack-deploy/workspace/deployment/install/linux-rhel7-x86_64/gcc-6.4.0/python-3.6.5-sltypv/bin/python3.6' '-s' 'setup.py' '--no-user-cfg' 'build'
/gpfs/bbp.cscs.ch/apps/hpc/test/kumbhar/spack-deploy/workspace/deployment/install/linux-rhel7-x86_64/gcc-6.4.0/python-3.6.5-sltypv/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'summary'
  warnings.warn(msg)
Traceback (most recent call last):
  File "setup.py", line 201, in <module>
    setup_package()
  File "setup.py", line 194, in setup_package
    'parquet-compare = spykfunc.tools.parquet_compare:run',
  File "/gpfs/bbp.cscs.ch/apps/hpc/test/kumbhar/spack-deploy/workspace/deployment/install/linux-rhel7-x86_64/gcc-6.4.0/py-setuptools-40.2.0-xnmc6t/lib/python3.6/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/gpfs/bbp.cscs.ch/apps/hpc/test/kumbhar/spack-deploy/workspace/deployment/install/linux-rhel7-x86_64/gcc-6.4.0/python-3.6.5-sltypv/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/gpfs/bbp.cscs.ch/apps/hpc/test/kumbhar/spack-deploy/workspace/deployment/install/linux-rhel7-x86_64/gcc-6.4.0/py-setuptools-40.2.0-xnmc6t/lib/python3.6/site-packages/setuptools/dist.py", line 370, in __init__
    k: v for k, v in attrs.items()
  File "/gpfs/bbp.cscs.ch/apps/hpc/test/kumbhar/spack-deploy/workspace/deployment/install/linux-rhel7-x86_64/gcc-6.4.0/python-3.6.5-sltypv/lib/python3.6/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/gpfs/bbp.cscs.ch/apps/hpc/test/kumbhar/spack-deploy/workspace/deployment/install/linux-rhel7-x86_64/gcc-6.4.0/py-setuptools-40.2.0-xnmc6t/lib/python3.6/site-packages/setuptools/dist.py", line 529, in finalize_options
    ep.load()(self, ep.name, value)
  File "/gpfs/bbp.cscs.ch/apps/hpc/test/kumbhar/spack-deploy/workspace/deployment/install/linux-rhel7-x86_64/gcc-6.4.0/py-setuptools-scm-3.1.0-4shgsa/lib/python3.6/site-packages/setuptools_scm/integration.py", line 23, in version_keyword
    dist.metadata.version = get_version(**value)
  File "/gpfs/bbp.cscs.ch/apps/hpc/test/kumbhar/spack-deploy/workspace/deployment/install/linux-rhel7-x86_64/gcc-6.4.0/py-setuptools-scm-3.1.0-4shgsa/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 142, in get_version
    parsed_version = _do_parse(config)
  File "/gpfs/bbp.cscs.ch/apps/hpc/test/kumbhar/spack-deploy/workspace/deployment/install/linux-rhel7-x86_64/gcc-6.4.0/py-setuptools-scm-3.1.0-4shgsa/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 111, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
LookupError: setuptools-scm was unable to detect version for '/gpfs/bbp.cscs.ch/ssd/slurmTmpFS/kumbhar/191456/spack-stage/spack-stage-raWCUP/Spykfunc'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
==> Error: ProcessError: Command exited with status 1:
    '/gpfs/bbp.cscs.ch/apps/hpc/test/kumbhar/spack-deploy/workspace/deployment/install/linux-rhel7-x86_64/gcc-6.4.0/python-3.6.5-sltypv/bin/python3.6' '-s' 'setup.py' '--no-user-cfg' 'build'
See build log for details:
  /gpfs/bbp.cscs.ch/apps/hpc/test/kumbhar/spack-deploy/workspace/HOME_DIR/spack/var/spack/stage/spykfunc-0.11.0-x6wl5osfi6nexkherkaxrbgwkz3ydjk3/Spykfunc/spack-build.out
```
